# ESET 456 - Lab 5 Cloud IoT
# Tasks 3-5 Mosquitto -> Azure IoT Hub bridge
# Replace ALL values inside < > before use.
# Do NOT submit or share your SAS token.

connection azure-iot-hub
address <IOT_HUB_NAME>.azure-devices.net:8883
remote_clientid <DEVICE_ID>
remote_username <IOT_HUB_NAME>.azure-devices.net/<DEVICE_ID>/?api-version=2021-04-12
remote_password <FULL_SAS_TOKEN>

bridge_protocol_version mqttv311
bridge_cafile /etc/ssl/certs/ca-certificates.crt
bridge_tls_version tlsv1.2
bridge_insecure false
try_private false
cleansession true
start_type automatic
notifications false

# Task 3 - sensor telemetry mappings
topic "" out 0 esp32/sensor2/temp devices/<DEVICE_ID>/messages/events/?type=temperature
topic "" out 0 esp32/sensor2/humidity devices/<DEVICE_ID>/messages/events/?type=humidity

# Task 4/5 - Device Twin topics
# ESP32/Pi -> Azure
topic $iothub/twin/GET/# out 0
topic $iothub/twin/PATCH/properties/reported/# out 0

# Azure -> ESP32/Pi
topic $iothub/twin/res/# in 0
topic $iothub/twin/PATCH/properties/desired/# in 0
